version: "3.8"
services:

 minio_exporter:
    image: joepll/minio-exporter
    container_name: minio_exporter
    restart: always
    volumes:
       - /etc/localtime:/etc/localtime:ro
    environment:
     - MINIO_URL=http://host.local:9000
     - MINIO_ACCESS_KEY=loginname
     - MINIO_ACCESS_SECRET=password
    network_mode: "host"